src/Microsoft.AspNet.StaticFiles/FileExtensionContentTypeProvider.cs

Fixes : https://github.com/aspnet/StaticFiles/issues/28
@Eilon @vbnewb

Adding woff2 MIME type

---

test/Microsoft.AspNet.StaticFiles.Tests/StaticFileContextTest.cs
test/Microsoft.AspNet.StaticFiles.Tests/project.json

https://github.com/aspnet/Testing/pull/69
@NTaylorMullen

NullLogger moved location

---

build.cmd
build.sh
samples/StaticFileSample/project.json
src/Microsoft.AspNet.StaticFiles/SendFileMiddleware.cs
src/Microsoft.AspNet.StaticFiles/project.json
test/Microsoft.AspNet.StaticFiles.Tests/project.json

Prepping to be merged once ready.

Update aspnet50/aspnetcore50 => dnx50/dnxcore50.

---

test/Microsoft.AspNet.StaticFiles.Tests/StaticFileContextTest.cs

Reacting to FileSystem changes

---

src/Microsoft.AspNet.StaticFiles/project.json

I believe this also fixes #50.

depend on Logging.Interfaces instead

---

README.md

Fix AppVeyor token

---

test/Microsoft.AspNet.StaticFiles.Tests/DefaultFilesMiddlewareTests.cs
test/Microsoft.AspNet.StaticFiles.Tests/DirectoryBrowserMiddlewareTests.cs
test/Microsoft.AspNet.StaticFiles.Tests/StaticFileMiddlewareTests.cs
test/Microsoft.AspNet.StaticFiles.Tests/project.json

Adding windows specific tests

---

test/Microsoft.AspNet.StaticFiles.Tests/DefaultFilesMiddlewareTests.cs
test/Microsoft.AspNet.StaticFiles.Tests/DirectoryBrowserMiddlewareTests.cs
test/Microsoft.AspNet.StaticFiles.Tests/StaticFileMiddlewareTests.cs

Dispose FileWatcher in tests

---

test/Microsoft.AspNet.StaticFiles.Tests/StaticFileMiddlewareTests.cs

Add test to ensure 404 when wwwroot not set

---

src/Microsoft.AspNet.StaticFiles/DefaultFilesOptions.cs

Remove `[SuppressMessage]`

---

samples/StaticFileSample/Startup.cs
samples/StaticFileSample/hosting.json
samples/StaticFileSample/project.json
samples/StaticFileSample/wwwroot/web.config
test/Microsoft.AspNet.StaticFiles.Tests/StaticFileMiddlewareTests.cs
test/Microsoft.AspNet.StaticFiles.Tests/StaticFilesTestServer.cs

Reacting to https://github.com/aspnet/Hosting/pull/521

Reacting to hew Hosting API

---

samples/StaticFileSample/Startup.cs
src/Microsoft.AspNet.StaticFiles/DefaultFilesExtensions.cs
src/Microsoft.AspNet.StaticFiles/DirectoryBrowserExtensions.cs
src/Microsoft.AspNet.StaticFiles/FileServerExtensions.cs
src/Microsoft.AspNet.StaticFiles/StaticFileExtensions.cs
test/Microsoft.AspNet.StaticFiles.Tests/DefaultFilesMiddlewareTests.cs
test/Microsoft.AspNet.StaticFiles.Tests/DirectoryBrowserMiddlewareTests.cs
test/Microsoft.AspNet.StaticFiles.Tests/StaticFileMiddlewareTests.cs

Standardizing ConfigureOptions to lambda https://github.com/aspnet/Coherence-Signed/issues/144

Standardizing middleware to use configureOptions lambda

---

.gitignore
.travis.yml
build.cmd
build.sh
makefile.shade
test/Microsoft.AspNet.StaticFiles.Tests/project.json

Build with dotnet

---

NuGetPackageVerifier.json
src/Microsoft.AspNetCore.StaticFiles/DefaultFilesMiddleware.cs
src/Microsoft.AspNetCore.StaticFiles/DirectoryBrowserMiddleware.cs
src/Microsoft.AspNetCore.StaticFiles/StaticFileMiddleware.cs
src/Microsoft.AspNetCore.StaticFiles/project.json

Enabled xml doc generation

---

README.md
src/Microsoft.AspNetCore.StaticFiles/project.json

Fix package metadata

---

samples/StaticFileSample/Startup.cs
samples/StaticFileSample/project.json
samples/StaticFileSample/web.config
samples/StaticFileSample/wwwroot/web.config

Review: @Tratcher 
RC2 Approval: @Eilon @DamianEdwards

Move web.config and use ANCM

---

samples/StaticFileSample/project.json
test/Microsoft.AspNetCore.StaticFiles.Tests/project.json

Migrate tests/samples/tools to portable

---

samples/StaticFileSample/project.json
samples/StaticFileSample/web.config

Update web.config and add publish tool

---

test/Microsoft.AspNetCore.StaticFiles.Tests/StaticFilesTestServer.cs
test/Microsoft.AspNetCore.StaticFiles.Tests/project.json

Part of https://github.com/aspnet/PlatformAbstractions/issues/34

Replace PlatformAbstractions with RuntimeInformation

---

src/Microsoft.AspNetCore.StaticFiles/DirectoryBrowserMiddleware.cs
test/Microsoft.AspNetCore.StaticFiles.Tests/DirectoryBrowserMiddlewareTests.cs

Fixes https://github.com/aspnet/StaticFiles/issues/139
@Tratcher

Make encoders registration optional

---

src/Microsoft.AspNetCore.StaticFiles/StaticFileContext.cs
test/Microsoft.AspNetCore.StaticFiles.Tests/CacheHeaderTests.cs

Adds tests to https://github.com/aspnet/StaticFiles/pull/144
@Tratcher

Fix If-Unmodified-Since - Incorrect condition

---

NuGet.config
src/Microsoft.AspNetCore.StaticFiles/StaticFileContext.cs

Reacting to https://github.com/aspnet/HttpAbstractions/pull/695. Built and tested locally.

Update static files to use strong comparison on ETags

---

src/Microsoft.AspNetCore.StaticFiles/FileExtensionContentTypeProvider.cs

Update woff2 media type

---

src/Microsoft.AspNetCore.StaticFiles/Helpers.cs
src/Microsoft.AspNetCore.StaticFiles/HtmlDirectoryFormatter.cs
src/Microsoft.AspNetCore.StaticFiles/StaticFileContext.cs

Use HttpMethods helpers

---

shared/Microsoft.AspNetCore.RangeHelper.Sources/RangeHelper.cs
src/Microsoft.AspNetCore.StaticFiles/StaticFileContext.cs
test/Microsoft.AspNetCore.RangeHelper.Sources.Test/Microsoft.AspNetCore.RangeHelper.Sources.Test.csproj
test/Microsoft.AspNetCore.RangeHelper.Sources.Test/RangeHelperTests.cs

Related to PR https://github.com/aspnet/Mvc/pull/7163

Add logging to RangeHelper.cs

---

shared/Microsoft.AspNetCore.RangeHelper.Sources/RangeHelper.cs

Removed temporary method from RangeHelper

---

StaticFiles.sln
build/dependencies.props
test/Microsoft.AspNetCore.StaticFiles.FunctionalTests/StaticFileMiddlewareTests.cs

Only the enum rename from WebListener to HttpSys here.

React to IntegrationTesting changes

---

test/Microsoft.AspNetCore.StaticFiles.FunctionalTests/StaticFileMiddlewareTests.cs

Hopefully this will shine some light on https://github.com/aspnet/Home/issues/3468 the next time it fails.

Add logging to functional tests
